image: docker:stable

stages:
  - build_service_jobad_reader_image
  - build_service_rss_reader_image

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker info

build_service_jobad_reader_image:
  stage: build_service_jobad_reader_image
  script:
    - docker build -t $CI_REGISTRY_IMAGE/service/service-jobad-reader ./service-jobad-reader
    - docker push $CI_REGISTRY_IMAGE/service/service-jobad-reader:latest

build_service_rss_reader_image:
  stage: build_service_rss_reader_image
  script:
    - docker build -t $CI_REGISTRY_IMAGE/service/service-rss-reader ./service-rss-reader
    - docker push $CI_REGISTRY_IMAGE/service/service-rss-reader:latest