From mongo:4.0.6
#ENV MONGO_INITDB_ROOT_USERNAME root
#ENV MONGO_INITDB_ROOT_PASSWORD root
#ENV MONGO_INITDB_DATABASE admin
# ADD init.js /docker-entrypoint-initdb.d/
EXPOSE 27017
VOLUME ./local/db/service-rss-reader/data:/data/db
