From mongo:4.0.6
ENV MONGO_INITDB_ROOT_USERNAME service-jobad-reader
ENV MONGO_INITDB_ROOT_PASSWORD pass
ENV MONGO_INITDB_DATABASE jobad-dev
ADD init-compose.js /docker-entrypoint-initdb.d/
EXPOSE 27017
VOLUME ../../local/db/data/service-jobad-reader:/data/db
